KEYCLOAK-16511 Update app-profile-jee-html5 QS
keycloak/keycloak-quickstarts pull request #228
Opened 2021-02-09 19:14 UTC by mhajas

- load the Keycloak JS adapter from the Keycloak server (If we want to have keycloak.js hardcoded in code I can revert)
- using chrome headless in testsuite
- replace aud with azp in test (This was changed here: https://issues.redhat.com/browse/KEYCLOAK-8483)

2021-02-10 13:29 UTC, mhajas commented
I tested it also with GHA and it is passing now. I needed to do a lot of stabilization there. I am not sure I did it correctly, maybe we should rather update test-helper package with some magic.

2021-03-05 10:03 UTC, vmuzikar requested changes
@mhajas Sorry for late review. Changes look good to me, nice stuff!

Could you please just update the README with instructions on how to run the tests, similarly to e.g. [here](https://github.com/keycloak/keycloak-quickstarts/blob/latest/user-storage-simple/README.md#integration-test-of-the-quickstart)?

2021-03-08 16:05 UTC, mhajas commented
@vmuzikar done

2021-03-08 16:20 UTC, vmuzikar approved these changes
@mhajas Thanks, LGTM now!

@abstractj Could you please merge this?

2021-04-09 15:28 UTC, vmuzikar requested changes

2021-04-09 15:28 UTC, vmuzikar commented on app-profile-jee-html5/src/test/java/org/keycloak/quickstart/ArquillianProfileJeeHtml5Test.java
>          webDriver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
@mhajas During further GH Actions testing I've found a test instability. Could you please add the following line which should fix it?
```java
webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
```

2021-04-09 17:09 UTC, abstractj commented
@mhajas once we managed to get the changes suggested by @vmuzikar, this PR is good to merge.

2021-04-12 09:36 UTC, vmuzikar approved these changes
@mhajas Thanks for the update!

@abstractj Could you please merge?

2021-04-30 15:27 UTC, abstractj approved these changes

2021-04-30 15:27 UTC, merged