KEYCLOAK-16534 Quickstart verification set for Product and Project running on Jenkins
keycloak/keycloak-quickstarts pull request #251
Opened 2021-06-22 15:19 UTC by lhanusov

@vmuzikar @pdrozd

2021-06-22 15:22 UTC, vmuzikar requested changes
@lhanusov Thank you! Haven't yet checked the changes but GH Actions seem to be broken.

2021-06-23 15:45 UTC, vmuzikar reviewed
Thank you, @lhanusov! Nice work!

One thing I'm wondering about is whether we should move the scripts from the `.github` dir to somewhere else (maybe `.scripts` or `.tests`?). It's no longer used by GH Actions only.

2021-06-23 15:45 UTC, vmuzikar commented on .github/scripts/run-tests.sh
> +if [ ! -n "$PRODUCT" ] || [ "$PRODUCT" == "false" ]; then
I don't like so many identical IFs here (`if [ ! -n "$PRODUCT" ] || [ "$PRODUCT" == "false" ]; then
`). :) Not sure what to do about this, though. Maybe create some list of excluded QS in prod and handle it in `run_tests`? Or at least group the excluded QS into a single IF?

2021-06-23 15:45 UTC, vmuzikar commented on .github/scripts/build-quickstarts.sh
> +fi
Just a nitpick. I think we could set some `$DIST` var in this IF and use it later when copying the authz-js-policies. That would save us from one more ugly IF. :)

2021-06-23 15:52 UTC, vmuzikar requested changes
Additionally, we need to fix the GH Actions which are still failing.

2021-06-24 08:03 UTC, lhanusov commented
@vmuzikar please, check the latest changes

2021-06-28 08:20 UTC, vmuzikar approved these changes
@lhanusov Thanks for the update! LGTM, approving.

There's one more thing though – **please DO NOT MERGE YET**. The KC GH Actions also [use the moved scripts](https://github.com/keycloak/keycloak/blob/512bcd14f76aed02c1bd668d434cc5ee59a57932/.github/workflows/ci.yml#L411-L418). Could you please create a PR to reflect the changes there as well? **It'll have to be merged together with this.**

2021-06-28 09:50 UTC, vmuzikar commented
Needs to be merged with https://github.com/keycloak/keycloak/pull/8212

2021-07-06 11:26 UTC, merged