Quarkus/OIDC update to app-profile-jee-vanilla
keycloak/keycloak-quickstarts pull request #380
Opened 2023-03-03 17:12 UTC by Toma5OD

Changes made to ReadMe.md, pom.xml, Controller.java and web.xml.

File created app-profile-jee-vanilla/src/main/webapp/WEB-INF/oidc.json

Readme should be easily followed and understood. Application should be fully functional with Wildfly 27.

2023-03-07 08:21 UTC, pskopek commented
@Toma5OD thanks for the PR. It needs to be placed against main branch (instead of the latest one).
You would like to reabase it as well as the last commit did change the pom.xml.

2023-03-07 08:26 UTC, pskopek requested changes

2023-03-07 08:26 UTC, pskopek commented on app-profile-jee-vanilla/README.md
> +The `app-profile-jee-vanilla` quickstart demonstrates how to change a JavaEE application that is secured with basic authentication without any changes to the WAR itself. Changing the authentication m
The "JavaEE" should not be used here as we have transitioned to Jakarta EE.

2023-03-07 08:26 UTC, pskopek commented on app-profile-jee-vanilla/README.md
> +The `app-profile-jee-vanilla` quickstart demonstrates how to change a JavaEE application that is secured with basic authentication without any changes to the WAR itself. Changing the authentication m
The change of authentication method is not done automatically with Elytron OIDC adapter. This should be rephrased.

2023-03-09 17:56 UTC, vmuzikar reviewed
I believe this should target `main` instead of `latest`. Please see: https://github.com/keycloak/keycloak-quickstarts/blob/06db58ad5748c874f808419582382d8b829dcdfa/CONTRIBUTING.md?plain=1#L74-L78

2023-03-10 02:58 UTC, closed without merging