Validate / fix user-storage-jpa
keycloak/keycloak-quickstarts pull request #387
Opened 2023-03-09 20:25 UTC by vramik

Closes keycloak/keycloak#17392
Closes keycloak/keycloak#17391

2023-03-15 16:37 UTC, ahus1 requested changes
Hi @vramik - thank you for making this work with tests for the Quarkus distribution!

See below for some comment. I didn't find the time to start it manually today; I plan to do this for the next review iteration. 

Please see below for some comments.

2023-03-15 16:37 UTC, ahus1 commented on user-storage-jpa/src/test/resources/MANIFEST.MF
Could this file be removed? I don't think it is used by the Quarkus dist.

2023-03-16 18:37 UTC, vramik commented on user-storage-jpa/README.md
> +1. Make sure you have an Keycloak server running with installed provider and with an admin user in the `master` realm. Your <span>Keycloak</span> should be listening on `http://localhost:8180/auth`.
> Could we make this run in a more standard way without the` /auth`? The only other project that would need to change would be the startup and the `user-storage-simple`, which we "own" as well AFAIK + the startup of Keycloak for the tests.

Good point, unfortunately it's as straightforward as it seems. QS tests uses classes (`FluentTestsHelper` and `TestsHelper`) from main keycloak repo which are shared with testsuite there. There may be a way to configure different base url, it needs to be investigated.

Considering it, I'd suggest to tackle it in separate issue.

2023-03-16 19:40 UTC, vramik commented on user-storage-jpa/README.md
> +1. Make sure you have an Keycloak server running with installed provider and with an admin user in the `master` realm. Your <span>Keycloak</span> should be listening on `http://localhost:8180/auth`.
https://github.com/keycloak/keycloak-quickstarts/issues/389

2023-03-17 08:04 UTC, ahus1 commented on user-storage-jpa/src/test/resources/MANIFEST.MF
Thanks, resolved.

2023-03-17 08:04 UTC, ahus1 commented on user-storage-jpa/README.md
> +1. Make sure you have an Keycloak server running with installed provider and with an admin user in the `master` realm. Your <span>Keycloak</span> should be listening on `http://localhost:8180/auth`.
Thanks, resolved.

2023-03-17 08:40 UTC, ahus1 approved these changes
Thank you for making these quick starts work again!

I've now also tested this manually, they work, and it is ready to be merged.

2023-03-17 08:43 UTC, mhajas approved these changes
Approving per @ahus1 's approval

2023-03-17 08:43 UTC, merged