Reviewing Node.js documentation
keycloak/keycloak-quickstarts pull request #439
Opened 2023-05-17 12:54 UTC by pedroigor

2023-05-17 14:03 UTC, mposolda requested changes
@pedroigor LGTM, but I think that extensions are not tested with your latest changes in CI? Looks like `Extension Quickstarts Tests` is testing the javascript/nodejs stuff (exactly same lie `JavaScript Quickstarts Tests` .

Added some tips inline how to possibly fix CI. Can you check?

2023-05-17 19:01 UTC, pedroigor commented on .github/workflows/ci.yml
> +
Ok

2023-05-17 19:01 UTC, pedroigor commented
@mposolda I've used the wrong template to build the extension job ... It should be fine now.

2023-05-18 06:04 UTC, mposolda approved these changes

2023-05-18 06:04 UTC, merged