Replace KC_URL also in keycloak.json
keycloak/keycloak-quickstarts pull request #569
Opened 2024-07-01 11:51 UTC by mhajas

It seems by default `keycloak.json` response does not have any content-type set and per docs https://github.com/bfncs/string-replace-middleware?tab=readme-ov-file#configuration [string-replace-middleware](https://github.com/bfncs/string-replace-middleware) does not apply string replacement in such case. 

This PR changes the behavior so also `keycloak.json` gets KC_URL replaced and hence can be use the same way as URL in index.html.

2024-10-14 16:01 UTC, mposolda commented
@jonkoops Could you please review? Feel free to close if it is already out-of-context by your latest changes.

2024-10-14 16:03 UTC, jonkoops requested changes
As per the [contribution guidelines](https://github.com/keycloak/keycloak-quickstarts/blob/latest/CONTRIBUTING.md) please target the `main` branch and not the `latest` branch.

2024-10-14 16:04 UTC, jonkoops commented
@mposolda the changes for the Node.js side might still be relevant, but I believe my recent changes have made the rest no longer relevant.

2024-10-15 11:53 UTC, mhajas commented
Thanks for looking into this @jonkoops. I see keycloak.json is no longer used so I am not 100% sure how to fix this now. I think we can close and leave this as is.

2024-10-15 11:53 UTC, closed without merging