initial version of the custom admin ui
keycloak/keycloak-quickstarts pull request #626
Opened 2024-11-26 12:05 UTC by edewit

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-11-27 07:44 UTC, stianst reviewed
Is this mechanism of extending the admin console considered a fully supported feature? or rather more preview or even experimental?

If this is considered fully supported, how can we ensure backwards compatibility for custom UIs. From my dummy knowledge of React it seems that it's not likely that we can.

2024-12-11 09:56 UTC, edewit commented
As long as we don't change the names of the components that we share, I don't see why we can't

2024-12-11 12:34 UTC, ssilvert requested changes
Need to change account references to admin references.

2025-01-24 14:08 UTC, ssilvert approved these changes

2025-01-28 12:41 UTC, merged